### ISSUE TITLE
Maths behind suicide burn.

### ISSUE THREAD

**Issue by Janik-ux** [CalebJ2/kOS-landing-script#2]
Hi @CalebJ2,
my question is not about an Issue in your code, but about the Maths behind it. Could you please explain, why are you writing `SHIP:AVAILABLETHRUST / SHIP:MASS - g.` in line 59 to set maxVertAccel? 

I tried to do a suicide burn autonomously for a long time and never got the right burnDist. 

This was my way to set maxVertAccel:` TWR * g - g + drag`
Where _TWR_ is `ship:availablethrust / (mass * g)` and _drag_ your function `scalarProj(SHIP:SENSORS:ACC, UP:VECTOR)`.

Are I adapting it right?
I would be very glad if you (or someone who understands this) could help me!

**Comment by CalebJ2** [comment]
Sorry, didn't see this. In case you still care:

Your equation can be simplified to my equation plus drag: `SHIP:AVAILABLETHRUST / SHIP:MASS - g + drag`

Ignoring drag like I did causes the rocket to start its burn too soon. Your equation assumes drag will be very large (this equation is used when near terminal velocity so it will likely be `g`) for the entire burn, which will cause the rocket to start its burn too late.

You need to approximate the average drag over the duration of the burn, which will be a bit less than `drag / 2`.

**Comment by Janik-ux** [comment]
Ahh thanks, I simply did it without drag, but maybe I'll look into it. The idea with approximation is very good. I always tried to compute the drag numericly while flying. Thanks again and happy coding ;)
